"use client"
import { emphasize, styled } from "@mui/material/styles";
import Breadcrumbs from "@mui/material/Breadcrumbs";
import Chip from "@mui/material/Chip";
import HomeIcon from "@mui/icons-material/Home";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import React, { useEffect, useState } from "react";
import { Box, Container, Grid, Typography, Skeleton } from "@mui/material";
import Link from "next/link";
import { AboutService } from "../service/AboutService";

const metadata = {
  title: "About | eShop",
  description: "Generated by create next app",
};

const StyledBreadcrumb = styled(Chip)(({ theme }) => ({
  backgroundColor:
    theme.palette.mode === "light"
      ? theme.palette.grey[100]
      : theme.palette.grey[800],
  height: theme.spacing(3),
  color: theme.palette.text.primary,
  fontWeight: theme.typography.fontWeightRegular,
  "&:hover, &:focus": {
    backgroundColor: emphasize(
      theme.palette.mode === "light"
        ? theme.palette.grey[100]
        : theme.palette.grey[800],
      0.06
    ),
  },
  "&:active": {
    boxShadow: theme.shadows[1],
    backgroundColor: emphasize(
      theme.palette.mode === "light"
        ? theme.palette.grey[100]
        : theme.palette.grey[800],
      0.12
    ),
  },
}));

const Page = () => {
  const [data, setData] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  async function fetchData() {
    try {
      const result = await AboutService();
      console.log(result.abouts);
      setData(result.abouts);
    } catch (error) {
      console.error("Error fetching data: ", error);
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <Box sx={{ background: "hotpink" }}>
        <Container>
          <Box sx={{ pt: 5, pb: 5 }}>
            <Breadcrumbs aria-label="breadcrumb">
              <Link href="/">
                <StyledBreadcrumb
                  component="a"
                  label="Home"
                  icon={<HomeIcon fontSize="large" />}
                />
              </Link>
              <StyledBreadcrumb
                component="a"
                href="/about"
                label="About Us"
                icon={<ExpandMoreIcon />}
              />
            </Breadcrumbs>
            <Typography variant="h4" sx={{ mt: 4 }}>
              About Us
            </Typography>
          </Box>
        </Container>
      </Box>
      <Box sx={{ mt: "2rem" }}>
        <Grid container spacing={2}>
          <Grid item xs={12} md={6}>
            <img
              src="https://img.freepik.com/free-vector/online-shopping-concept-landing-page_52683-11240.jpg?size=626&ext=jpg&uid=R121733695&ga=GA1.1.248855276.1696004271&semt=ais"
              alt="Customer Support"
              style={{ width: "100%" }}
            />
          </Grid>
          <Grid item xs={12} md={6} sx={{ alignItems: "center" }}>
            {isLoading ? ( // Show skeleton loading when data is being fetched
              <Skeleton variant="rectangular" width={200} height={20} />
            ) : (
              data.map((response, index) => (
                <div key={index}>
                  <h1>{response.title}</h1>
                  <p>{response.description}</p>
                  <button onClick={() => setIsLoading(true)}>Get More</button>
                </div>
              ))
            )}
          </Grid>
        </Grid>
      </Box>
    </div>
  );
};

export default Page;
